title: Jon Villasurda Jr.
description: >-
  Official site for Jon Villasurda Jr., a Senior Principal in healthcare and
  government benefits consulting at Mercer in Michigan.
url: https://jonvillasurdajr.github.io
lang: en-US
author:
  name: Jon Villasurda Jr.
social_links:
  github: https://github.com/jonvillasurdajr
  linkedin: https://www.linkedin.com/in/jon-villasurda-jr-54817619
  chrt: https://chrt.org/bio/jon-villasurda/

